//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Arabic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Arabic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Arabic", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحجز بنجاح.
        /// </summary>
        internal static string Bookedsuccessfully {
            get {
                return ResourceManager.GetString("Bookedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحجز غير ممكن في هذا الوقت الحالي.
        /// </summary>
        internal static string BookingNotPossible {
            get {
                return ResourceManager.GetString("BookingNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء الموعد بنجاح.
        /// </summary>
        internal static string CancelledSuccessfully {
            get {
                return ResourceManager.GetString("CancelledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact AR Department.
        /// </summary>
        internal static string CARD {
            get {
                return ResourceManager.GetString("CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation Can&apos;t be done for the same Department on the Same Day.
        /// </summary>
        internal static string CCDSDSD {
            get {
                return ResourceManager.GetString("CCDSDSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collectable Configuration NOT defined Contact AR Department.
        /// </summary>
        internal static string CCNDCARD {
            get {
                return ResourceManager.GetString("CCNDCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Contract Date has been Expired.
        /// </summary>
        internal static string CompanyContractDateExpired {
            get {
                return ResourceManager.GetString("CompanyContractDateExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company assigned to the Patient is Blocked..
        /// </summary>
        internal static string CompanyPatientBlocked {
            get {
                return ResourceManager.GetString("CompanyPatientBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company assigned to the Patient is Expired..
        /// </summary>
        internal static string CompanyPatientExpired {
            get {
                return ResourceManager.GetString("CompanyPatientExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Bill not Possible for Patient.
        /// </summary>
        internal static string Creditbillnotpossibleforpatient {
            get {
                return ResourceManager.GetString("Creditbillnotpossibleforpatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأوقات المحددة غير متوفرة أو متداخلة مع مواعيد أخرى.
        /// </summary>
        internal static string Error759 {
            get {
                return ResourceManager.GetString("Error759", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد لديك موعد مسبقا مع طبيب بنفس التخصص وفي نفس اليوم.
        /// </summary>
        internal static string Error760 {
            get {
                return ResourceManager.GetString("Error760", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الموعد متداخل مع موعدك مع طبيب آخر.
        /// </summary>
        internal static string Error761 {
            get {
                return ResourceManager.GetString("Error761", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما في إلغاء الموعد.
        /// </summary>
        internal static string ErroronCancelAppointment {
            get {
                return ResourceManager.GetString("ErroronCancelAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل عرض تقرير المختبر.
        /// </summary>
        internal static string FailedLabGroupReporttodisplay {
            get {
                return ResourceManager.GetString("FailedLabGroupReporttodisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل عرض تقرير المختبر.
        /// </summary>
        internal static string FailedLabReporttodisplay {
            get {
                return ResourceManager.GetString("FailedLabReporttodisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل عرض التقرير الطبي.
        /// </summary>
        internal static string FailedMedicalCertificateReporttodisplay {
            get {
                return ResourceManager.GetString("FailedMedicalCertificateReporttodisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed  to display Prescription Report.
        /// </summary>
        internal static string FailedPrescriptionReporttodisplay {
            get {
                return ResourceManager.GetString("FailedPrescriptionReporttodisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل عرض تقرير الأشعة.
        /// </summary>
        internal static string FailedRadiologyReporttodisplay {
            get {
                return ResourceManager.GetString("FailedRadiologyReporttodisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Generate Bill.
        /// </summary>
        internal static string FAILGBILL {
            get {
                return ResourceManager.GetString("FAILGBILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Grade has been Blocked.
        /// </summary>
        internal static string GradeBlocked {
            get {
                return ResourceManager.GetString("GradeBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Card Expired ! Credit bill not possible.
        /// </summary>
        internal static string ICECBNP {
            get {
                return ResourceManager.GetString("ICECBNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Card Expired.
        /// </summary>
        internal static string InsuranceCardExpired {
            get {
                return ResourceManager.GetString("InsuranceCardExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance associated with Patient Company is Expired..
        /// </summary>
        internal static string InsuranceCompanyPatientExpired {
            get {
                return ResourceManager.GetString("InsuranceCompanyPatientExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز كلمة المرور لمرة واحدة غير صحيح.
        /// </summary>
        internal static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter of Authority Validity Date has been Expired.
        /// </summary>
        internal static string LAVDE {
            get {
                return ResourceManager.GetString("LAVDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOA not mapped.
        /// </summary>
        internal static string LOANM {
            get {
                return ResourceManager.GetString("LOANM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Appointment is Available to Generate Bill.
        /// </summary>
        internal static string NoAPPGBill {
            get {
                return ResourceManager.GetString("NoAPPGBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found to Generate Bill.
        /// </summary>
        internal static string NORECGBILL {
            get {
                return ResourceManager.GetString("NORECGBILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد سجلات.
        /// </summary>
        internal static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير صحيحة.
        /// </summary>
        internal static string NotValidPassword {
            get {
                return ResourceManager.GetString("NotValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز التسجيل غير صحيح.
        /// </summary>
        internal static string NotValidRegCode {
            get {
                return ResourceManager.GetString("NotValidRegCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل إرسال رمز كلمة مرور صالحة لمرة واحدة.
        /// </summary>
        internal static string OTPSentFailed {
            get {
                return ResourceManager.GetString("OTPSentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما عند إرسال رمز كلمة مرور صالحة لمرة واحدة.
        /// </summary>
        internal static string OTPSentFailedError {
            get {
                return ResourceManager.GetString("OTPSentFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال رمز كلمة مرور صالحة لمرة واحدة بنجاح.
        /// </summary>
        internal static string OTPSentSuccessfully {
            get {
                return ResourceManager.GetString("OTPSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال رمز كلمة مرور صالحة لمرة واحدة إلى رقم الجوال المسجل.
        /// </summary>
        internal static string OTPSentToMobile {
            get {
                return ResourceManager.GetString("OTPSentToMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية تغيير كلمة المرور.
        /// </summary>
        internal static string PasswordChangeFail {
            get {
                return ResourceManager.GetString("PasswordChangeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور بنجاح.
        /// </summary>
        internal static string PasswordChangeSuccess {
            get {
                return ResourceManager.GetString("PasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient is currently EMR.
        /// </summary>
        internal static string PatientcurrentlyEMR {
            get {
                return ResourceManager.GetString("PatientcurrentlyEMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Is Currently IP.
        /// </summary>
        internal static string PatientcurrentlyIP {
            get {
                return ResourceManager.GetString("PatientcurrentlyIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient is having Outstanding Amount:.
        /// </summary>
        internal static string PatientOutstandingAmount {
            get {
                return ResourceManager.GetString("PatientOutstandingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التسجيل بنجاح.
        /// </summary>
        internal static string RegisteredSuccessfully {
            get {
                return ResourceManager.GetString("RegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اعادة جدولة الموعد و التعديل بنجاح.
        /// </summary>
        internal static string RescheduleSuccessfully {
            get {
                return ResourceManager.GetString("RescheduleSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما أثناء حفظ رمز كلمة المرورالصالحة لمرة واحدة.
        /// </summary>
        internal static string SomeerroroccuredwhileSavinggeneratedOTP {
            get {
                return ResourceManager.GetString("SomeerroroccuredwhileSavinggeneratedOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما أثناء حفظ  المستخدم الجديد.
        /// </summary>
        internal static string SomeerroroccuredwhileSavingnewuser {
            get {
                return ResourceManager.GetString("SomeerroroccuredwhileSavingnewuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية التحقق بنجاج.
        /// </summary>
        internal static string VerificationSuccess {
            get {
                return ResourceManager.GetString("VerificationSuccess", resourceCulture);
            }
        }
    }
}
